name: app_01
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  http: ^1.2.2
  path: ^1.9.0
  path_provider: ^2.1.3
  provider: ^6.1.2
  shared_preferences: ^2.2.3
  sqflite: ^2.3.3+1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0
  
flutter:
  fonts:
      - family: PlaywriteMX
        fonts:
          - asset: fonts/PlaywriteMX-Regular.ttf
          - asset: fonts/PlaywriteMX-Thin.ttf
          - asset: fonts/PlaywriteMX-ExtraLight.ttf
          - asset: fonts/PlaywriteMX-Light.ttf
  assets:
    - images/PurpleFlower.jpg
    - images/WhiteFlower.jpg
    - images/bluePlace.png
    - images/phone.png


  uses-material-design: true
